// All user-facing copy (Hebrew). Wording rules: docs/product-spec.md — never "safe", always "visual".
export const he = {
  appName: 'סורק פירות וירקות',
  cameraHint: 'צלמו פרי או ירק אחד, מקרוב ובאור טוב',
  scan: 'סריקה',
  analyzing: 'בודק…',
  permissionTitle: 'צריך גישה למצלמה',
  permissionBody: 'האפליקציה מצלמת את הפרי כדי להעריך אותו. התמונה מעובדת במכשיר ואינה נשמרת.',
  permissionButton: 'אישור גישה',
  noEngine: 'המודל אינו זמין במכשיר הזה.',
  error: 'משהו השתבש. נסו שוב.',
  ripeness: 'בשילות',
  freshness: 'טריות',
  spoilage: 'סימני קלקול',
  recommendation: 'המלצה',
  confidence: 'ביטחון בזיהוי',
  notAvailable: 'לא זמין עדיין לסוג זה',
  whatWeSaw: 'מה זיהינו?',
  why: 'מה גרם למודל לחשוב כך?',
  retake: 'צילום נוסף',
  wasItRight: 'האם הזיהוי נכון?',
  yes: 'כן',
  no: 'לא',
  thanks: 'תודה! המשוב עוזר לשפר את המודל.',
  credits: 'קרדיט לנתונים',
  creditsIntro: 'המודל אומן על מאגרי תמונות ציבוריים באישור הרישיון שלהם:',
  modelVersion: 'גרסת מודל',
  visualOnlyBanner: 'הערכה חזותית בלבד',
};
